# Generated by Django 6.0.3 on 2026-04-22 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('closed', 'Завершена')], default='active', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('cat_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels_as_a', to='cats.cat', verbose_name='Кот А')),
                ('cat_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels_as_b', to='cats.cat', verbose_name='Кот Б')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_duels', to=settings.AUTH_USER_MODEL, verbose_name='Создатель дуэли')),
            ],
            options={
                'verbose_name': 'Дуэль',
                'verbose_name_plural': 'Дуэли',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('chosen_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.cat', verbose_name='Выбранный кот')),
                ('duel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='cats.duel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Голос',
                'verbose_name_plural': 'Голоса',
                'unique_together': {('duel', 'user')},
            },
        ),
    ]
