# Generated by Django 6.0.3 on 2026-04-23 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_duel_vote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='duel',
            name='cat_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels_as_a', to='cats.cat'),
        ),
        migrations.AlterField(
            model_name='duel',
            name='cat_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels_as_b', to='cats.cat'),
        ),
        migrations.AlterField(
            model_name='duel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='duel',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_duels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='duel',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('closed', 'Завершена')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='duel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
